name: Waka Readme

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  schedule:
    # Runs at 12am UTC daily
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: Update this repo's README with WakaTime stats
    runs-on: ubuntu-latest # Specifies the runner environment
    steps:
      - name: Checkout repository # Checks out your repository under $GITHUB_WORKSPACE, so the job can access it
        uses: actions/checkout@v2
      - name: Update README with WakaTime stats
        uses: athul/waka-readme@master # Points to the action that updates the README with your WakaTime stats
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # Uses your WakaTime API key stored in secrets

